# simple attention mechanism

### import required packges

In [1]:
import numpy as np
import torch
import math

#### get the input

In [4]:
# input string
input_str = "your journey starts with one step"

In [10]:
# get the embedding of all tokens
inputs = torch.tensor([
   [0.43, 0.15, 0.89], # Your
   [0.55, 0.87, 0.66], # journey ----targeting this word
   [0.57, 0.85, 0.64], # starts
   [0.22, 0.58, 0.33], # with
   [0.77, 0.25, 0.10], # one
   [0.05, 0.80, 0.55]  # step
])

inputs.shape

torch.Size([6, 3])

In [11]:
inputs.shape[0]

6

In [19]:
check = torch.empty(inputs.shape[0])
check

tensor([0., 0., 0., 0., 0., 0.])

In [14]:
# take journey (inputs[1] as an example)
query = inputs[1]
query

tensor([0.5500, 0.8700, 0.6600])

## calculate attention score

In [16]:
# attention score of journey wrt all embeddings
attention_scores_journey = torch.empty(inputs.shape[0])

# calculate the attention score with all emebediings
for index, embedding in enumerate(inputs):
    attention_scores_journey[index] = torch.dot(embedding, query)

    
attention_scores_journey    

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [20]:
attention_scores_journey.sum()

tensor(6.5617)

## calculate the Attention weight

In [21]:
# get the total attention scores
attention_scores_journey_sum = attention_scores_journey.sum()
attention_scores_journey_sum

tensor(6.5617)

In [22]:
# get the attention weights
attention_weights_journey = attention_scores_journey/attention_scores_journey_sum
attention_weights_journey

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [23]:
attention_weights_journey.sum()

tensor(1.0000)

## Apply Softmax

In [27]:
weights = [0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656]

#calaculate e_total
e_total = 0
for value in weights:
    e_total += math.exp(value)


e_total, value

(7.095585327648173, 0.1656)

In [28]:
# divide every value in the weights  by e_total
normalized_weights = [math.exp(value)/e_total for value in weights]
normalized_weights

[0.163005260478708,
 0.17698809548436997,
 0.17647557352350096,
 0.16025759240191018,
 0.15695866228968697,
 0.16631481582182409]

In [31]:
def my_softmax(x):
    return torch.exp(x) / torch.exp(x).sum (dim = 0)


my_softmax(torch.tensor(weights))   

tensor([0.1630, 0.1770, 0.1765, 0.1603, 0.1570, 0.1663])

In [33]:
## using pytorch softmax
normalized_weights = torch.softmax(torch.tensor(weights), dim=0)
normalized_weights

tensor([0.1630, 0.1770, 0.1765, 0.1603, 0.1570, 0.1663])

In [34]:
normalized_weights.sum()

tensor(1.0000)