# Tensor boolean Masking

## import required pkg

In [1]:
import numpy as np
import torch

## create a tensor

In [2]:
vector = torch.tensor([10,20,30,40,50,60])

In [3]:
vector

tensor([10, 20, 30, 40, 50, 60])

## boolean Indexing

In [5]:
# [10,20, 30]

vector[[True, False, True, True, False, False]]

tensor([10, 30, 40])

## filtering the tensor

In [6]:
# broadcasting
vector > 30

tensor([False, False, False,  True,  True,  True])

In [7]:
vector[vector > 30]

tensor([40, 50, 60])